In [71]:
import numpy as np
board = np.zeros((10,5),dtype=int)

I_piece_0 = np.array([[-2,0],[-1,0],[0,0],[1,0]])
I_piece_90 = np.array([[0,-2],[0,-1],[0,0],[0,1]])
I_piece_180 = np.array([[-2,-1],[-1,-1],[0,-1],[1,-1]])
I_piece_270 = np.array([[-1,-2],[-1,-1],[-1,0],[-1,1]])

L_piece_0 = np.array([[-1,0],[-1,1],[0,1],[1,1]])
L_piece_90 = np.array([[-1,2],[0,2],[0,1],[0,0]])
L_piece_180 = np.array([[-1,1],[0,1],[1,1],[1,2]])
L_piece_270 = np.array([[0,2],[0,1],[0,0],[1,0]])

S_piece_0 = np.array([[-1,0],[0,0],[0,1],[1,1]])
S_piece_90 = np.array([[0,1],[0,0],[1,0],[1,-1]])
S_piece_180 = np.array([[-1,-1],[0,-1],[0,0],[1,0]])
S_piece_270 = np.array([[-1,1],[-1,0],[0,0],[0,-1]])


Z_piece = np.array([[-1,1],[0,1],[0,0],[1,0]])
Z_piece_90 = np.array([[0,-1],[0,0],[1,0],[1,1]])
Z_piece_180 = np.array([[-1,0],[0,0],[0,-1],[1,-1]])
Z_piece_270 = np.array([[-1,-1],[-1,0],[0,0],[0,1]])



J_piece = np.array([[-1,1],[-1,0],[0,0],[1,0]])
J_piece_90 = np.array([[0,1],[0,0],[0,-1],[1,1]])
J_piece_180 = np.array([[-1,0],[0,0],[1,0],[1,-1]])
J_piece_270 = np.array([[-1,-1],[0,-1],[0,0],[0,1]])

O_piece = np.array([[0,0],[1,0],[0,1],[1,1]])

T_piece_0 = np.array([[-1,0],[0,0],[0,1],[1,0]])
T_piece_90 = np.array([[0,1],[0,0],[0,-1],[1,0]])
T_piece_180 = np.array([[-1,0],[0,0],[0,-1],[1,0]])
T_piece_270 = np.array([[-1,0],[0,0],[0,1],[0,-1]])





I_piece_rotations = {
	0:I_piece_0,
	90:I_piece_90,
	180:I_piece_180,
	270:I_piece_270,
}
L_piece_rotations = {
	0:L_piece_0,
	90:L_piece_90,
	180:L_piece_180,
	270:L_piece_270,
}
S_piece_rotations = {
	0:S_piece_0,
	90:S_piece_90,
	180:S_piece_180,
	270:S_piece_270,
}
Z_piece_rotations = {
	0:Z_piece,
	90:Z_piece_90,
	180:Z_piece_180,
	270:Z_piece_270,

}
J_piece_rotations = {
	0:J_piece,
	90:J_piece_90,
	180:J_piece_180,
	270:J_piece_270,

}
O_piece_rotations = {
	0:O_piece,
	90:O_piece,
	180:O_piece,
	270:O_piece,
}
T_piece_rotations = {
	0:T_piece_0,
	90:T_piece_90,
	180:T_piece_180,
	270:T_piece_270,
}


codes_pieces = {
	1:I_piece_rotations,
	2:L_piece_rotations,
	3:S_piece_rotations,
	4:Z_piece_rotations,
	5:J_piece_rotations,
	6:O_piece_rotations,
	7:T_piece_rotations,
}


color_pieces = {
	1:cyan,
	2:orange,
	3:green,
	4:salmon,
	5:blue,
	6:yellow,
	7:purple,
}
types_pieces = {
	1:"I_piece",
	2:"L_piece",
	3:"S_piece",
	4:"Z_piece",
	5:"J_piece",
	6:"O_piece",
	7:"T_piece",
}

class piece:


	def __init__(self,type, starting_position) -> None:
		self.x = starting_position[0]
		self.y = starting_position[1]
		self.type = type
		self.color = color_pieces[type]
		self.rotation = 0
		self.shape = codes_pieces[type][self.rotation]


		self.max_x=max(self.shape[:,0])
		self.min_x=min(self.shape[:,0])
		self.max_y=max(self.shape[:,1])
		self.min_y=min(self.shape[:,1])

		self.grounded = False


		print(f"{types_pieces[self.type]} created at {self.x},{self.y}")

	def x_up_bound(self):
		return max(self.shape[:,0])+self.x
	def x_down_bound(self):
		return min(self.shape[:,0])+self.x
	def y_up_bound(self):
		return max(self.shape[:,1])+self.y
	def y_down_bound(self):
		return min(self.shape[:,1])+self.y

	def __str__(self) -> str:
		return str(types_pieces[self.type])
	
	def board_position(self):
		squares=np.copy(self.shape)
		squares[:,0]+=self.x
		squares[:,1]+=self.y

		indices=tuple(squares.T)
		return indices
	

	def rotate(self):
		self.rotation = (self.rotation+ 90) % 360
		self.shape = codes_pieces[self.type][self.rotation]
		self.max_x=max(self.shape[:,0])
		self.min_x=min(self.shape[:,0])
		self.max_y=max(self.shape[:,1])
		self.min_y=min(self.shape[:,1])

		rotation_allowed = True
		indices=self.board_position()


		if (self.y_down_bound()<0 ):
			self.y = -self.min_y
			print('out of bounds in x')

		if (self.y_up_bound()>board.shape[1]-1):
			self.y = board.shape[1]-1-self.max_y
			print('out of bounds in x')

		if (self.x_down_bound()<0 ):
			self.x = -self.min_x
			print('out of bounds in y')

		if (self.x_up_bound()>board.shape[0]-1):
			self.x = board.shape[0]-1-self.max_x
			print('out of bounds in y')

		print(self.board_position())

print('----0')
piece1=piece(7,[7,2])
board[piece1.board_position()]=piece1.type
print(np.flipud(board.T))
print('----90')
board=board*0
piece1.rotate()

board[piece1.board_position()]=piece1.type
print(np.flipud(board.T))
print('----180')
board=board*0
piece1.rotate()

board[piece1.board_position()]=piece1.type
print(np.flipud(board.T))
print('----270')
board=board*0
piece1.rotate()
board[piece1.board_position()]=piece1.type
print(np.flipud(board.T))
print('----0')
board=board*0
piece1.rotate()
board[piece1.board_position()]=piece1.type
print(np.flipud(board.T))

 

----0
T_piece created at 7,2
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 7 7 7 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
----90
(array([7, 7, 7, 8]), array([3, 2, 1, 2]))
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 7 7 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
----180
(array([6, 7, 7, 8]), array([2, 2, 1, 2]))
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 7 7 7 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
----270
(array([6, 7, 7, 7]), array([2, 2, 3, 1]))
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 7 7 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
----0
(array([6, 7, 7, 8]), array([2, 2, 3, 2]))
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 7 7 7 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [86]:
piece1.board_position()

(array([6, 7, 7, 8]), array([2, 2, 3, 2]))

In [85]:
board2=np.zeros((5,10),dtype=int)
board2[:,0]=1
board2[:,1]=1
print(np.flipud(board2.T))
print(np.where(np.all(board2 != 0, axis=0))[0])

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[0 1]


In [93]:
ground=np.zeros((5,10),dtype=int)
ground[:,3]=1
ground[:,0]=1
lines_cleared=np.array([1,2])
ground[:,lines_cleared]=ground[:,lines_cleared]*0
print(np.flipud(ground.T))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [1 1 1 1 1]]
