In [16]:
import numpy as np

# Assuming z is a 2D numpy array
z=np.ones((10,10),dtype=int)
q=np.zeros((10,10),dtype=int)
q[1,1]=1
w=np.array([[0,0],[0,1],[1,1],[2,1]])

w2=np.copy(w)
new_value=0
x=5
y=3
w2[:,0]=w2[:,0]+x
w2[:,1]=w2[:,1]+y
indices=tuple(w2.T)
z[indices]=new_value
print(z)


[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 0 0 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1]
 [1 1 1 1 0 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [18]:
z=abs(z-1)
z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [14]:
def add_arrays_with_condition_np(z, q):
    if z.shape != q.shape:
        raise ValueError("Arrays must have the same shape")

    # Create a mask where both arrays are non-zero
    mask = np.logical_and(z != 0, q != 0)

    # If any element in the mask is True, raise a flag
    flag = np.any(mask)

    # Use the mask to set the corresponding elements in q to 0
    q_masked = np.where(mask, 0, q)

    # Add the arrays
    result = z + q_masked

    return result, flag

In [19]:
result, flag = add_arrays_with_condition_np(z, q)
print(result)
print(flag)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
False
